// Generated by CoffeeScript 1.7.1
var autoIncrement;

autoIncrement = require('mongoose-auto-increment');

module.exports = function(mongoose, Schema) {
  var Joke, JokeSchema;
  JokeSchema = new Schema({
    title: String,
    content: String,
    pic_url: String,
    base_id: Number,
    from: String
  });
  mongoose.plugin(autoIncrement.plugin, 'joke');
  return Joke = mongoose.model('user_base', JokeSchema);
};
