// Generated by CoffeeScript 1.7.1
var autoIncrement;

autoIncrement = require('mongoose-auto-increment');

module.exports = function(mongoose, Schema) {
  var Joke, JokeSchema;
  JokeSchema = new Schema({
    title: {
      type: String,
      "default": ""
    },
    content: {
      type: String,
      "default": ""
    },
    pic_url: {
      type: String,
      "default": ""
    },
    base_id: {
      type: Number,
      "default": 0
    },
    from: {
      type: String,
      "default": ""
    }
  });
  mongoose.plugin(autoIncrement.plugin, 'joke');
  return Joke = mongoose.model('joke', JokeSchema);
};
