// Generated by CoffeeScript 1.7.1
var autoIncrement;

autoIncrement = require('mongoose-auto-increment');

module.exports = function(mongoose, Schema) {
  var Joke, JokeSchema;
  JokeSchema = new Schema({
    joke_id: {
      type: Number,
      "default": 0
    },
    user_id: String
  });
  mongoose.plugin(autoIncrement.plugin, 'user');
  return Joke = mongoose.model('user', JokeSchema);
};
