// Generated by CoffeeScript 1.7.1
var joke_controller;

joke_controller = require('./controller/joke_controller');

module.exports = function(route) {
  route.text('hello', function(data, req, res, next) {
    console.log('hello text event');
    return res.reply('hello world');
  });
  route.text(['help', 'h', '帮助'], function(data, req, res, next) {
    return res.reply("hello 测试命令\njoke 笑话");
  });
  return route.text(['joke', '笑话'], joke_controller.joke);
};
