// Generated by CoffeeScript 1.7.1
var joke_controller;

joke_controller = require('./controller/joke_controller');

module.exports = function(app) {
  app.post('/joke/new', joke_controller["new"]);
  return app.get('/joke/new', joke_controller["new"]);
};
